CREATE TABLE "MEMBER" ( 
   "MEMBER_NO"   NUMBER PRIMARY KEY,
   "MEMBER_EMAIL"   VARCHAR2(50) NOT NULL,
   "MEMBER_PW"   VARCHAR2(100) NOT NULL,
   "MEMBER_NAME"   VARCHAR2(30) NOT NULL,
   "MEMBER_TEL"   CHAR(11) NOT NULL,
   "MEMBER_ADDR"   VARCHAR2(500),
   "PROFILE_IMG"   VARCHAR2(200),
   "ENROLL_DT"   DATE DEFAULT SYSDATE ,
   "SECESSION_FL"   CHAR(1)   DEFAULT 'N'
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS '회원 번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_EMAIL" IS '회원 이메일(아이디)';
COMMENT ON COLUMN "MEMBER"."MEMBER_PW" IS '회원 비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS '회원 이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_TEL" IS '전화번호(- 미포함)';
COMMENT ON COLUMN "MEMBER"."MEMBER_ADDR" IS '회원 주소';
COMMENT ON COLUMN "MEMBER"."PROFILE_IMG" IS '회원 프로필 이미지';
COMMENT ON COLUMN "MEMBER"."ENROLL_DT" IS '회원 가입일';
COMMENT ON COLUMN "MEMBER"."SECESSION_FL" IS '탈퇴여부(Y:탈퇴, N:미탈퇴)';

CREATE SEQUENCE SEQ_MEMBER_NO;

CREATE TABLE EMAIL_CERTIFICATION(
   "EMAIL" VARCHAR2(50) NOT NULL,
   "C_NUMBER" CHAR(6) NOT NULL,
   "ISSUE_DT" DATE DEFAULT SYSDATE
);

SELECT COUNT(*)
FROM EMAIL_CERTIFICATION
WHERE EMAIL = leatakim@naver.com;

SELECT * FROM MEMBER;

DROP TABLE MEMBER;

DROP SEQUENCE SEQ_MEMBER_NO;

SELECT MEMBER_NO, MEMBER_EMAIL, MEMBER_NAME, MEMBER_TEL, MEMBER_ADDR, PROFILE_IMG,
			   TO_CHAR(ENROLL_DT, 'YYYY-MM-DD HH24:MI:SS') AS ENROLL_DT, MEMBER_PW
FROM MEMBER
WHERE MEMBER_EMAIL = 'leatakim@daum.net'
AND SECESSION_FL = 'N'